spring.application.name=actuator
server.port=8085

# This exposes all actuator endpoints
# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,info,beans
management.info.env.enabled=true

info.app.name=Actuator
info.app.description=Actuator Demo

first.name=Sachin
last.name=Tendulkar

