spring.application.name=crud
server.port=8085

# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore
spring.datasource.username=bookstore
spring.datasource.password=bookstore

# To Turn Off Spring Boot Banner
spring.main.banner-mode=off

# Logging
# At Production Environment, this is a good choice
# At times of developing or debugging, use INFO or DEBUG
logging..level.root=warn

# Logging Configs to view SQL Statements
# logging.level.org.hibernate.SQL=debug
# logging.level.org.hibernate.orm.jdbc.bind=trace

# Configure JPS/Hibernate to auto create tables
# Not RECOMMENDED in PRODUCTION Environment
# It might change the schema
# Use this in Development or Testing purposes
# spring.jpa.hibernate.ddl-auto=create

